// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json







// Visualizer descriptors

// Add requirejs paths
config.requirejsPaths = {
  'petri-net-webgme-app': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/petri_net_webgme_app';
validateConfig(config);
module.exports = config;
